[package]
name = "rs-covid19gr"
version = "0.1.0"
authors = ["l-const <const-l@outlook.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
serde = "1.0"